### ISSUE TITLE
Some minor notes

### ISSUE THREAD

**Issue by hpanago** [dtsioumas/macspoofer#1]
1) On line 16, "NEWMAC=`echo ${VENDORBYTES}:${NONVENDORBYTES}`"  there is no need to "echo"
2) Also the script needs root privileges so, either the commands will run with sudo, or the entire script will be run by root ( there can be checks for the user that runs it, and exit if it is the wrong one).

Good job.

**Comment by dtsioumas** [comment]
@hpanago Thanks for your feedback :). I 'll fix this issues
